services:
  app1:
    image: yismaili/app1:latest
    container_name: app1
    networks:
      - app-network
    restart: unless-stopped

  app2:
    image: yismaili/app2:latest
    container_name: app2
    networks:
      - app-network
    restart: unless-stopped

  load-balancer:
    image: nginx:latest
    container_name: my-lb
    ports:
      - "80:80"
    volumes:
      - ./conf/nginx-ip-routing.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app-network
    depends_on:
      - app1
      - app2
    restart: unless-stopped

networks:
  app-network:
    driver: bridge