version: "3.8"
services:
  postgres_db:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
