version: '3.8'

services:
  frontend:
    image: node:18-alpine
    container_name: frontend
    working_dir: /app
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://BACKEND_PRIVATE_IP:3001
    ports:
      - "3000:3000"
      - "80:80"
    volumes:
      - ./app:/app
      - /app/node_modules
    command: npm start
    restart: unless-stopped
    networks:
      - frontend-net

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
    restart: unless-stopped
    networks:
      - frontend-net

networks:
  frontend-net:
    driver: bridge